ENV_CONFIG=dev
ENVIRONMENT=dev
AZURE_SUBSCRIPTION="Breast Screening - Manage Breast Screening - Dev"
HUB_SUBSCRIPTION="Digital Screening DToS - DevOps"
HUB=dev
TERRAFORM_MODULES_REF=main
ENABLE_SOFT_DELETE=false
ADO_MANAGEMENT_POOL=private-pool-dev-uks
CLOUD_API_HOSTNAME=dev.manage-breast-screening.non-live.screening.nhs.uk
SCREENING_ENTRA_GROUP_ID="f20d9f9a-b1ac-4875-a5e1-f9dfc0307c34"
