ENV_CONFIG=preprod
ENVIRONMENT=preprod
AZURE_SUBSCRIPTION="Breast Screening - Manage Breast Screening - PreProd"
HUB_SUBSCRIPTION="Digital Screening DToS - Core Services Prod Hub"
HUB=prod
TERRAFORM_MODULES_REF=main
ENABLE_SOFT_DELETE=true
ADO_MANAGEMENT_POOL=private-pool-prod-uks
CLOUD_API_HOSTNAME=preprod.manage-breast-screening.nhs.uk
SCREENING_ENTRA_GROUP_ID="ab8fd001-2722-4118-9659-3d4425db7894"
GATEWAY_RINGS="ring1"
