ENV_CONFIG=review
ENVIRONMENT=review
AZURE_SUBSCRIPTION="Breast Screening - Manage Breast Screening - Dev"
HUB_SUBSCRIPTION="Digital Screening DToS - DevOps"
HUB=dev
TERRAFORM_MODULES_REF=main
ENABLE_SOFT_DELETE=false
ADO_MANAGEMENT_POOL=private-pool-dev-uks
CLOUD_API_HOSTNAME=review.manage-breast-screening.non-live.screening.nhs.uk
SCREENING_ENTRA_GROUP_ID="14f915c3-ef0a-471b-b9bf-31187d18f8b6"
