ENV_CONFIG=review
ENVIRONMENT=review
AZURE_SUBSCRIPTION="Breast Screening - Manage Breast Screening - Dev"
HUB_SUBSCRIPTION="Digital Screening DToS - DevOps"
HUB=dev
TERRAFORM_MODULES_REF=main
ENABLE_SOFT_DELETE=false
ADO_MANAGEMENT_POOL=private-pool-dev-uks
CLOUD_API_HOSTNAME=review.manage-breast-screening.non-live.screening.nhs.uk
