ENV_CONFIG=prod
ENVIRONMENT=prod
AZURE_SUBSCRIPTION="Breast Screening - Manage Breast Screening - Prod"
HUB_SUBSCRIPTION="Digital Screening DToS - Core Services Prod Hub"
TERRAFORM_MODULES_REF=main
HUB=prod
ENABLE_SOFT_DELETE=true
ADO_MANAGEMENT_POOL=private-pool-prod-uks
CLOUD_API_HOSTNAME=manage-breast-screening.nhs.uk
# ring1 = first real sites (one per PACS vendor)
# To onboard more rings: set GATEWAY_RINGS="ring0 ring1 ring2 ..." in this file
GATEWAY_RINGS="ring1"
